### ISSUE TITLE
Missing Variables

### ISSUE THREAD

**Issue by BrutalBirdie** [ebbba-org/ansible-role-greenlight#3]
Role Expects:

```yaml
---
bbb_endpoint: "https://<sub.domain.tld>/bigbluebutton/api/"
scalelite_loadbalancer_secrets:
  greenlight: "<YOUR_SECRET>"
bbb_enable_recordings: false
```
These vars should be role specific but can be tried to grepped from the ebbba bbb role but should not default to.
